# Generated by Django 5.1.6 on 2025-05-06 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='recurrence',
            new_name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='interval',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
