# Generated by Django 5.1.6 on 2025-06-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
