# Generated by Django 5.1.6 on 2025-07-14 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]), blank=True, help_text='Days of the week this task recurs on. 0=Sun, 6=Sat', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
