# Generated by Django 5.1.6 on 2025-07-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_recurrencerule_days_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='start_date',
        ),
    ]
