# Generated by Django 4.2.20 on 2025-10-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_remove_recurrencerule_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('title_override', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='goals.task')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('parent', 'due_date')},
            },
        ),
    ]
