# Generated by Django 4.2.20 on 2025-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_taskinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
